// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// bizOrderDao is the data access object for the table xy_biz_order.
// You can define custom methods on it to extend its functionality as needed.
type bizOrderDao struct {
	*internal.BizOrderDao
}

var (
	// BizOrder is a globally accessible object for table xy_biz_order operations.
	BizOrder = bizOrderDao{internal.NewBizOrderDao()}
)

// Add your custom methods and functionality below.
