// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// bizOrderDetailsDao is the data access object for the table xy_biz_order_details.
// You can define custom methods on it to extend its functionality as needed.
type bizOrderDetailsDao struct {
	*internal.BizOrderDetailsDao
}

var (
	// BizOrderDetails is a globally accessible object for table xy_biz_order_details operations.
	BizOrderDetails = bizOrderDetailsDao{internal.NewBizOrderDetailsDao()}
)

// Add your custom methods and functionality below.
