// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// cmsChangelogDao is the data access object for the table xy_cms_changelog.
// You can define custom methods on it to extend its functionality as needed.
type cmsChangelogDao struct {
	*internal.CmsChangelogDao
}

var (
	// CmsChangelog is a globally accessible object for table xy_cms_changelog operations.
	CmsChangelog = cmsChangelogDao{internal.NewCmsChangelogDao()}
)

// Add your custom methods and functionality below.
