// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// migrationDao is the data access object for the table xy_migration.
// You can define custom methods on it to extend its functionality as needed.
type migrationDao struct {
	*internal.MigrationDao
}

var (
	// Migration is a globally accessible object for table xy_migration operations.
	Migration = migrationDao{internal.NewMigrationDao()}
)

// Add your custom methods and functionality below.
