// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// testDaoDao is the data access object for the table xy_test_dao.
// You can define custom methods on it to extend its functionality as needed.
type testDaoDao struct {
	*internal.TestDaoDao
}

var (
	// TestDao is a globally accessible object for table xy_test_dao operations.
	TestDao = testDaoDao{internal.NewTestDaoDao()}
)

// Add your custom methods and functionality below.
